spring:
  application:
    name: auth
  datasource:
    username: ${db.username}
    password: ${db.password}
    url: ${db.url}
  jpa:
    open-in-view: false

app:
  jwt-secret: ${jwt-secret}
  jwt-validity: ${jwt-expiration}
